apiVersion: v1
kind: Service
metadata:
  name: hive-metastore
  labels:
    app: hive-metastore
spec:
  ports:
  - name: thrift
    port: 9083
  - name: rest
    port: 9001
  selector:
    app: hive-metastore
