apiVersion: v1
kind: ConfigMap
metadata:
  name: hadoop-config
data:
  core-site.xml: |
    <configuration>
      <property>
        <name>fs.s3a.endpoint</name>
        <value>http://ozone-s3g-rest:9878</value>
      </property>
      <property>
        <name>fs.s3a.path.style.access</name>
        <value>true</value>
      </property>
      <property>
        <name>fs.s3a.change.detection.version.required</name>
        <value>false</value>
      </property>
      <property>
        <name>fs.s3a.change.detection.mode</name>
        <value>none</value>
      </property>
    </configuration>
